import ImmuneBlock from './atoms/ImmuneBlock';
import '../static/css/Immune.scss';

const Immune = () => {
    return (
        <div className="Immune">
            <div className="Immune_inner">
                <div className="Immune_bg">
                    <div className="Immune_Info">
                        <h3>Works where optical sensors fail</h3>
                        <p>
                            Optical devices often fail in the presence of dust, smoke, water or swarf generated by production processes. The
                            Inxpect team is highly specialized in radar technology, and has designed sophisticated FMCW radar algorithms
                            capable of filtering these types of disturbances to reduce false alarms and increase productivity.
                        </p>
                    </div>
                </div>
                <ImmuneBlock />
            </div>
        </div>
    );
};

export default Immune;
